### PR TITLE
Adding functionality for Walking on Land, swimming in Water, climbing Ladders and a few more

### PR DESCRIPTION
**Pull request by nano13**
Just to say "hello!". Maybe you are interested in having a look at my changes?

### CODE REVIEW

**Comment by rbarongr** [comment]
Hi, I've taken a look at your changes. Seems like you have implemented a lot of functionalities.

I haven't tested the code, but I have read it and I could give you some comments about it if you want.

**Comment by nano13** [comment]
Hi! Thanks for your effort to look at the code! Yes, I would really appreciate your feedback!

**Comment by rbarongr** [comment]
So...

- Seems like you have chosen to go for the state machine approach to control the behaviour depending on the situation on the player body, that's a good solution for some cases but I just find yours a bit complex for what it is trying to resolve. There are too many states for movement and jumping. If someone read the code for the first time, like I did, it's weird that so many states are needed. I can see you want to control the fact the player is on a ladder or on water, I just think there can be simplifications and not so many states should be needed. Also for jumping, the names of the states are not very clear, thankfully you commented the functionality, but, again I don't think so many states should be needed.
- The battle of IFs statements: when you are dealing with states machines you need to act according to the current state, that's true, but when you have so many states you are incrementing the code complexity and lowering the code maintainability. Godot have [the match statement](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#match) that can helps a bit cleaning up your code for better readability, and a bit the maintainability. You should change the branching of states from pure IF-ELIF-ELSE to use the match statement.
- States machines can have other implementation in Godot: [you can find here](https://www.gdquest.com/tutorial/godot/design-patterns/finite-state-machine/) how to implemente a state machine using Nodes and transitions, maybe you can take a look at it.
- Delegate functionality: you have just one script with about 400 lines, in my opinion that's too much (sometimes is needed but at least here you could get it shorter). For example: the camera movement can be implemented purely in a script attach to the player camera, and all of the camera functionality can be removed from the player script. This helps organizing the controller giving it modularity, and, when you want to update/change the camera movement you go to a script that just have the camera controls, nothing else.
- Ladder and water surface Area3Ds: you take care of player states according to being inside or outside Area3D for the ladders and the water, that's fine, the problem I see is that these scripts directly access and changes the states of the player, this change should be made in the player script and the area should only call _that_ function of the player script. That's just good practise.
- Think about this: what happens if I want to remove the ladder functionality? I would have to go to so many states and lines of code, and debugging it to be sure that is working fine without ladders would take so long. That's why modularity is key and giving the chance to other developers to add/remove functionalities easily would be nice. Of course... that's not an easy task in many cases.

Hey... if it works... You have put much time coding these changes. I hope you don't find my comments too harsh, maybe this code is just what your player controller needs for the game you want to build, or you are just experimenting with game development, and that's cool. **These kind of commits, building upon the base code I published, is exactly what I had in mind when I released the project**. These changes obviously go beyond a 'basic' FPC, so merging is out of the question. But this code may help other people, so thank you for sharing it. 😁

**Comment by nano13** [comment]
Thanks a lot for your feedback! I have tried to adapt my code according to your advices, work still in progress.

**Pull request closed without merging**
